### ISSUE TITLE
sorting does not have an effect on the selected rows

### ISSUE THREAD

**Issue by NucsuM** [kmhgmbh/vue-md-powerful-datatable#1]
Changing the sorting direction does not have an effect on selected row.

![screenshot_26](https://user-images.githubusercontent.com/7623214/35213265-5462c8da-ff5d-11e7-9a17-746ba7ebcb63.png)

![screenshot_27](https://user-images.githubusercontent.com/7623214/35213260-4d2f9f8e-ff5d-11e7-8789-db8cb30ae21b.png)

**Comment by marklabenski** [comment]
Fixed by commit 22fe5bc

**Comment by NucsuM** [comment]
In my view, the issue#1 is still open in 0.11.1. the gif shows the problem.

selecting "Birdy" -> changing the sorting direction 1 times, Rosa is selected but the Array still contains Birdy.

At the end of the gif you see  "selecting Birdy" does remove Birdy from the array.


![issue01](https://user-images.githubusercontent.com/7623214/35217267-d8065b68-ff6a-11e7-88b5-95fe5f6a6556.gif)

**Comment by marklabenski** [comment]
fixed with daacc87f53859bd0c6937bf1e8566ec67d9c8976
released in Version 0.11.2
