### ISSUE TITLE
can not sort in 0.13.0

### ISSUE THREAD

**Issue by NucsuM** [kmhgmbh/vue-md-powerful-datatable#4]
I generated a table with 20 Birds. If i press the sorting button (in the tablehead), nothing happen and firefox throw a warning. 

```
[Vue warn]: You may have an infinite update loop in watcher with expression "data"

found in

---> <VueMdPowerfulDatatable> at /Users/wrk/dev/kmh/vue-md-powerful-datatable/src/data-table/VueMdPowerfulDatatable.vue
       <MdLayout>
         <Root>
```

Interesting hint: in my project I also use the 0.13.0, and there firefox does not throw the warning and sorting works well.

**Comment by NucsuM** [comment]
Interesting hint: in my project I also use the 0.13.0, and there firefox does not throw the warning and sorting works.

**Comment by marklabenski** [comment]
Thanks for your detailed error description. 
Version 0.13.2 should fix this. Can you give it a try and send me feedback, please? Thanks!
40e55bd01b2a5623526041a441e3047fbc878a9e

**Comment by NucsuM** [comment]
tested in 0.13.2 -> the sorting function works
